# Generated by Django 6.0.7 on 2026-08-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='الاسم الكامل')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='اسم المستخدم')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='رقم الهاتف')),
                ('role', models.CharField(choices=[('admin', 'مدير النظام'), ('manager', 'مدير قسم'), ('employee', 'موظف')], default='employee', max_length=20, verbose_name='الصلاحية/الدور')),
                ('is_active', models.BooleanField(default=True, verbose_name='حساب نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ إنشاء الحساب')),
            ],
        ),
    ]
