# Generated by Django 6.0.7 on 2026-08-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم المنتج/الخدمة')),
                ('category', models.CharField(max_length=50, verbose_name='نوع المنتج أو القسم')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='الكمية المتوفرة')),
                ('is_available', models.BooleanField(default=True, verbose_name='متوفر للبيع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
            ],
        ),
    ]
